name: "Test our Nix setup"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    - uses: rrbutani/use-nix-shell-action@v1
      with:
        file: shell.nix
    - run: cabal build exe:gibbon
    - run: cabal test gibbon
