name: Test Gibbon examples
on:
  push: 
  pull_request:
  workflow_dispatch:
jobs:
  linux:
    name: test-gibbon
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: rrbutani/use-nix-shell-action@v1
        with:
          file: shell.nix

      - name: versions
        run: |
          $HC --version
          racket --version
          gcc --version
          stack --version
          cabal --version
      - run: cabal v2-update -w $HC
      - run: cabal v2-freeze -w $HC
      - name: cache-cabal
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-cabal-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-cabal-
          path: |
            ~/.cabal/store
            ~/.cabal/packages
            dist-newstyle
      - name: build
        run: |
          cd gibbon-compiler
          cabal v2-update -w $HC
          cabal v2-build -w $HC .
      - name: cache-answers
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-answers
          path: gibbon-compiler/examples/build_tmp/*.ans
      - name: answers
        run: |
          cd gibbon-compiler
          make answers
      - name: list-answers
        run: |
          ls gibbon-compiler/examples/build_tmp/*.ans
      - name: tests
        run: |
          export GIBBONDIR=`pwd`
          cd gibbon-compiler/
          cabal v2-exec -w $HC test-gibbon-examples -- -v2
